"""Sentinel — APScheduler-driven daemon.

Run:
    python -m jarvis.apps.sentinel.scheduler

Schedules cron routines that watch inbox/calendar/atlas/news/school,
write to state/inbox.jsonl, and push alerts via Notifier.

Sentinel is infrastructure, not an agent — it drives the six top-level
agents (tempo, atlas, lens, scholar, forge) on a schedule.
"""
from __future__ import annotations

import logging
import os
import signal
import sys
import time

from apscheduler.schedulers.blocking import BlockingScheduler

from jarvis.agents.atlas.agent import AtlasOrchestrator, AtlasUnavailableError
from jarvis.agents.lens.agent import Lens
from jarvis.agents.registry import AgentDescriptor, build_default_registry
from jarvis.agents.scholar.agent import Scholar
from jarvis.agents.tempo.agent import Tempo
from jarvis.contract import InboxEvent
from jarvis.core.triggers import scan_periodic
from jarvis.state import append_inbox

from .mission_control_bridge import sync_tick as mission_control_sync_tick
from .notifier import default_notifier
from .routines import (
    atlas_daily_rollup,
    atlas_tick,
    calendar_tick,
    daily_forge_tick,
    email_tick,
    heartbeat_tick,
    morning_digest,
    news_tick,
    scholar_tick,
)
from .voice_context_tick import voice_context_tick

log = logging.getLogger("sentinel")


def _build_subsystems(
    reg: dict[str, AgentDescriptor] | None = None,
) -> tuple[Tempo, AtlasOrchestrator, Lens, Scholar]:
    """Return live registry-backed agents.

    Sentinel ticks must hit the same agent instances the API serves so a
    degraded-mode read here matches what the dashboard reports. Previously
    this returned bare mocks, which made the daemon report a parallel
    fictitious world.

    If Atlas is unavailable the descriptor still wraps an ``AtlasOrchestrator``
    in auto-mock mode — the per-tick handlers below catch
    ``AtlasUnavailableError`` and emit a degraded-mode inbox event instead
    of crashing the scheduler thread.
    """
    registry = reg or build_default_registry()
    tempo = registry["tempo"].instance
    atlas = registry["atlas"].instance
    lens = registry["lens"].instance
    scholar = registry["scholar"].instance
    return tempo, atlas, lens, scholar


def _safe_tick(
    fn,  # type: ignore[no-untyped-def]
    label: str,
    *args,  # type: ignore[no-untyped-def]
    **kwargs,  # type: ignore[no-untyped-def]
):
    """Wrap a tick callable; swallow ``AtlasUnavailableError`` as a degraded event."""
    try:
        return fn(*args, **kwargs)
    except AtlasUnavailableError as exc:
        log.warning("%s: atlas unavailable — degraded inbox event (%s)", label, exc)
        append_inbox(
            InboxEvent(
                agent="atlas",
                severity="warn",
                summary=f"{label}: atlas unavailable — running degraded",
                ref={"error_class": type(exc).__name__, "error": str(exc)},
            )
        )
        return {"degraded": True, "error": str(exc)}
    except Exception:
        log.warning("%s: tick failed", label, exc_info=True)
        return {"degraded": True, "error": "tick_failed"}


def _triggers_tick(reg: dict, notifier=None) -> None:
    """Periodic job: run all polling-style trigger rules and emit InboxEvents.

    The notifier is passed through so warn/crit events generated by R2/R3/R4
    surface as Pushover/ntfy pushes the operator actually sees, not just dashboard
    entries that require the dashboard to be open.
    """
    try:
        fired = scan_periodic(reg, notifier=notifier)
        if fired:
            log.info("triggers_tick: %d trigger(s) fired", len(fired))
    except Exception:
        log.warning("triggers_tick failed", exc_info=True)


# Module-level state for Atlas health tracking (last known status)
_atlas_health_last: dict = {"healthy": None}


def atlas_health_tick(atlas_api_url: str) -> dict:
    """Check Atlas /system/health every 60s; push notification on 200↔503 transitions."""
    import httpx

    from jarvis.contract import InboxEvent
    from jarvis.state import append_inbox

    was_healthy = _atlas_health_last.get("healthy")
    try:
        resp = httpx.get(f"{atlas_api_url}/system/health", timeout=3.0)
        is_healthy = resp.status_code == 200
    except Exception:
        is_healthy = False

    transitioned = was_healthy is not None and was_healthy != is_healthy
    if transitioned:
        if not is_healthy:
            summary = "Atlas degraded — check agents"
            severity = "alert"
        else:
            summary = "Atlas recovered"
            severity = "info"
        append_inbox(InboxEvent(agent="sentinel", severity=severity, summary=summary))
        log.warning("atlas_health_tick: %s", summary)

    _atlas_health_last["healthy"] = is_healthy
    return {"healthy": is_healthy, "transitioned": transitioned}


# mission_control_sync_tick is scheduled every 30s but the upstream call is
# expensive; throttle to one successful sync per ``_MC_SYNC_MIN_INTERVAL_SEC``.
_MC_SYNC_MIN_INTERVAL_SEC = 60.0
_mc_sync_last_ts: float = 0.0


def _mc_sync_throttled() -> dict:
    """Run mission_control_sync_tick at most once per 60s window."""
    global _mc_sync_last_ts
    now = time.monotonic()
    if now - _mc_sync_last_ts < _MC_SYNC_MIN_INTERVAL_SEC:
        return {"skipped": True, "reason": "cooldown"}
    try:
        result = mission_control_sync_tick()
        _mc_sync_last_ts = now
        return result if isinstance(result, dict) else {"ok": True}
    except Exception:
        log.warning("mc_sync_tick failed", exc_info=True)
        return {"skipped": True, "reason": "error"}


def build_scheduler(scheduler: BlockingScheduler | None = None) -> BlockingScheduler:
    reg = build_default_registry()
    tempo, atlas, lens, scholar = _build_subsystems(reg)
    notifier = default_notifier()
    watchlist = [t.strip() for t in os.environ.get("JARVIS_WATCHLIST", "BTC,ETH").split(",") if t.strip()]

    sched = scheduler or BlockingScheduler(timezone="UTC")

    # Each tick is wrapped via _safe_tick so an offline Atlas (or any
    # transient subsystem error) emits a degraded inbox event instead of
    # crashing the APScheduler worker.
    sched.add_job(
        lambda: _safe_tick(email_tick, "email_tick", tempo, notifier),
        "interval", minutes=15, id="email",
    )
    sched.add_job(
        lambda: _safe_tick(calendar_tick, "calendar_tick", tempo, notifier),
        "interval", hours=1, id="calendar",
    )
    sched.add_job(
        lambda: _safe_tick(atlas_tick, "atlas_tick", atlas, notifier),
        "interval", minutes=5, id="atlas",
    )
    sched.add_job(
        lambda: _safe_tick(news_tick, "news_tick", lens, watchlist, notifier),
        "interval", minutes=30, id="news",
    )
    sched.add_job(
        lambda: _safe_tick(scholar_tick, "scholar_tick", scholar, notifier),
        "interval", hours=2, id="scholar",
    )
    sched.add_job(morning_digest, "cron", hour=8, minute=0,
                  args=[reg, notifier], id="morning")
    sched.add_job(morning_digest, "cron", hour=18, minute=0,
                  args=[reg, notifier], id="evening")
    sched.add_job(atlas_daily_rollup, "cron", hour=22, minute=0,
                  args=[atlas, notifier], id="atlas_rollup")
    sched.add_job(heartbeat_tick, "interval", seconds=60, args=[sched, notifier], id="heartbeat")
    sched.add_job(_mc_sync_throttled, "interval", seconds=30, id="mc_sync")
    sched.add_job(_triggers_tick, "interval", minutes=30, args=[reg, notifier], id="triggers")

    # Wire fire_for_event as an in-process inbox listener so events written from
    # this sentinel process (atlas_tick, scan_periodic, atlas_health_tick) trigger
    # the cross-agent reactions in jarvis/core/triggers.py. The API process
    # registers the same listener in its own startup path; dedup over a shared
    # state/triggers_fired.jsonl prevents double-firing.
    try:
        from jarvis.core.triggers import fire_for_event
        from jarvis.state import register_inbox_listener

        register_inbox_listener(
            lambda event: fire_for_event(reg, event, notifier=notifier)
        )
        log.info("sentinel: fire_for_event listener registered")
    except Exception:
        log.warning("sentinel: failed to register fire_for_event listener", exc_info=True)

    # Voice fact sheet refresh — feeds the cheap voice handler with current
    # pnl / mail counts / next event so quick queries skip subsystem fan-out.
    sched.add_job(voice_context_tick, "interval", minutes=5, id="voice_context")
    atlas_api_url = os.environ.get("JARVIS_ATLAS_API", "http://localhost:8000")
    sched.add_job(
        atlas_health_tick, "interval", seconds=60, args=[atlas_api_url], id="atlas_health"
    )
    # Daily autonomous Forge — picks news story, builds MVP, pushes to GitHub
    sched.add_job(
        daily_forge_tick,
        "cron",
        hour=10,  # 10:00 UTC == 06:00 ET (EDT-aware via misfire_grace)
        minute=0,
        args=[reg, notifier],
        id="daily_forge",
        max_instances=1,
        misfire_grace_time=3600,
    )

    return sched


def main() -> int:  # pragma: no cover
    logging.basicConfig(level=logging.INFO,
                        format="%(asctime)s %(levelname)s %(name)s: %(message)s")
    sched = build_scheduler()

    def _shutdown(signum, frame):
        log.info("shutting down…")
        sched.shutdown(wait=False)
        sys.exit(0)

    signal.signal(signal.SIGINT, _shutdown)
    signal.signal(signal.SIGTERM, _shutdown)

    log.info("sentinel started — %d jobs scheduled", len(sched.get_jobs()))
    try:
        sched.start()
    except (KeyboardInterrupt, SystemExit):
        pass
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
# end of scheduler.py
